#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://db4free.net:3306/yourfinancial?useSSL=false
#spring.datasource.username=financial
#spring.datasource.password=passer123
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
#spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true

spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/financial?useSSL=false
    username: financ
    password: Passer123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  #spring:
    #  datasource:
    #   url: jdbc:oracle:thin:@//localhost:1521/CCBSINGA
    #  username: FINANC
    # password: FINANC
    # driver-class-name: oracle.jdbc.OracleDriver

    # jpa:
    # database-platform: org.hibernate.dialect.Oracle12cDialect
    # generate-ddl: true
    #show-sql: true
      #hibernate:
    #  ddl-auto: update

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days